function ListElement(params) {
    return(
        <div className="listElement">
            <div className="elementTitel">Fortsetzung der Beteiligung bewaffneter deutscher Streitkräfte an der Multidimensionalen Integrierten Stabilisierungsmission der Vereinten Nationen in Mali (MINUSMA) auf Grundlage der Resolutionen 2100 (2013){params.title}</div>
            <div className="elementExtra">SomePerson, SomeAffiliation, 12.04.1988{params.speaker}{params.affiliation}{params.date}</div>
            <div className="textSample">...vor allem der Aufklärung, und mit bis zu 1 000 Soldatinnen und Soldaten. Die Bundeswehr erfüllt ihre Aufgaben bravourös. Sie agiert in einem sehr fordernden Umfeld. Im Sommer haben wir zwei unserer besten Tiger-Piloten bei einem tragischen Hubschrauberunglück...</div>
        </div>
    );
}
export default ListElement;

// {
//     // This ID is automatically generated by the crawler, as the official data source does not provide unique IDs for all speeches provided. This is a GUID as per GUID4 specification.
//     "id": "uuid",

//     // Title of the speech.
//     "title": "string",
    
//     // The name of the speaker.
//     "speaker": "string",

//     // Affiliation of the speaker. This can be his/her role in the Bundestag or for example his party.
//     "affiliation": "string",

//     // Date of the speech in a ISO 8601-1:2019 String Format.
//     "date": "Date in ISO 8601-1:2019 String Format",

//     // Entire processed content of the speech.
//     "text": "string"
// }