function ListElement(params) {
    return(
        <div className="listElement">
            <div className="elementTitel">{params.title}</div>
            <div className="elementExtra">{params.speaker}{params.affiliation}{params.date}</div>
            <div className="textSample">{params.sample}</div>
        </div>
    );
}
export default ListElement;

// {
//     // This ID is automatically generated by the crawler, as the official data source does not provide unique IDs for all speeches provided. This is a GUID as per GUID4 specification.
//     "id": "uuid",

//     // Title of the speech.
//     "title": "string",
    
//     // The name of the speaker.
//     "speaker": "string",

//     // Affiliation of the speaker. This can be his/her role in the Bundestag or for example his party.
//     "affiliation": "string",

//     // Date of the speech in a ISO 8601-1:2019 String Format.
//     "date": "Date in ISO 8601-1:2019 String Format",

//     // Entire processed content of the speech.
//     "text": "string"
// }