const mongoose = require('mongoose')
const Schema = mongoose.Schema

const Speech = new Schema(
    {
        // This ID is automatically generated by the crawler, as the official data source does not provide unique IDs for all speeches provided. This is a GUID as per GUID4 specification.

    // Title of the speech.
    "title": {type: String},
    
    // The name of the speaker.
    "speaker": {type: String},

    // Affiliation of the speaker. This can be his/her role in the Bundestag or for example his party.
    "affiliation": {type: String},

    // Date of the speech in the format dd.mm.yyyy
    "date": {type: [String]},

    // Entire processed content of the speech.
    "text": {type: String}
    }
)

module.exports = mongoose.model("speeches", Speech)